echo '{"country": "Italy","year": 2015,"type": "Gran Apasso","producer": "Puglia","quantity": 11,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2015,"type": "Gran Apasso","producer": "Puglia","quantity": 11,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2015,"type": "Nemorino (Red)","producer": "Il Giusti & Zanta","quantity": 12,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2015,"type": "Nemorino (Red)","producer": "Il Giusti & Zanta","quantity": 12,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2015,"type": "Maremma (Organic)","producer": "Prelius","quantity": 4,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2015,"type": "Maremma (Organic)","producer": "Prelius","quantity": 4,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2015,"type": "Tignanello","producer": "Antinori","quantity": 7,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2015,"type": "Tignanello","producer": "Antinori","quantity": 7,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2014,"type": "Rosso di Montalcino","producer": "Camigliano","quantity": 7,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2014,"type": "Rosso di Montalcino","producer": "Camigliano","quantity": 7,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2014,"type": "Chianti Classico Riserva","producer": "tenuta Di Arceno","quantity": 8,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2014,"type": "Chianti Classico Riserva","producer": "tenuta Di Arceno","quantity": 8,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Chianti Classico Riserva","producer": "Carpinetto","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Chianti Classico Riserva","producer": "Carpinetto","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Barolo","producer": "Cavallotto - Brico Boschis ","quantity": 12,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Barolo","producer": "Cavallotto - Brico Boschis ","quantity": 12,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Barolo","producer": "Arna","quantity": 7,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Barolo","producer": "Arna","quantity": 7,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Barbaresco","producer": "Orlando Abrigo - Meruzzano","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Barbaresco","producer": "Orlando Abrigo - Meruzzano","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Barolo","producer": "Pira - Serralunga","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Barolo","producer": "Pira - Serralunga","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2012,"type": "Brunello Di Montalcino","producer": "Siro Pacenti - Belogrilli","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2012,"type": "Brunello Di Montalcino","producer": "Siro Pacenti - Belogrilli","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2015,"type": "Toscana","producer": "Giodo","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2015,"type": "Toscana","producer": "Giodo","quantity": 6,"cellarLocation": "Front Panel","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine

echo '{"country": "Italy","year": 2006,"type": "Sassicaia","producer": "Sassicaia","quantity": 12,"cellarLocation": "Floor","bottleSize": null,"originalWoodenCase": true}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2006,"type": "Sassicaia","producer": "Sassicaia","quantity": 12,"cellarLocation": "Floor","bottleSize": null,"originalWoodenCase": true}' http://localhost:8081/wine

echo '{"country": "Italy","year": 2011,"type": "Toscano (red)","producer": "Crognolo","quantity": 6,"cellarLocation": "Right Front","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2011,"type": "Toscano (red)","producer": "Crognolo","quantity": 6,"cellarLocation": "Right Front","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2012,"type": "Brunello Di Montalcino","producer": "Altesimo","quantity": 1,"cellarLocation": "Right Front","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2012,"type": "Brunello Di Montalcino","producer": "Altesimo","quantity": 1,"cellarLocation": "Right Front","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Barolo","producer": "Arna - Cannabi Boschis","quantity": 1,"cellarLocation": "Right Front","bottleSize": 1500,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Barolo","producer": "Arna - Cannabi Boschis","quantity": 1,"cellarLocation": "Right Front","bottleSize": 1500,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1996,"type": "Barbaresco","producer": "Gaja ","quantity": 5,"cellarLocation": "Right Front","bottleSize": 1500,"originalWoodenCase": true}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1996,"type": "Barbaresco","producer": "Gaja ","quantity": 5,"cellarLocation": "Right Front","bottleSize": 1500,"originalWoodenCase": true}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2015,"type": "Sassicaia","producer": " ","quantity": 6,"cellarLocation": "Right Front","bottleSize": null,"originalWoodenCase": true}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2015,"type": "Sassicaia","producer": " ","quantity": 6,"cellarLocation": "Right Front","bottleSize": null,"originalWoodenCase": true}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2015,"type": "Nambrot","producer": "Renara di Grizzano","quantity": 6,"cellarLocation": "Right Front","bottleSize": null,"originalWoodenCase": true}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2015,"type": "Nambrot","producer": "Renara di Grizzano","quantity": 6,"cellarLocation": "Right Front","bottleSize": null,"originalWoodenCase": true}' http://localhost:8081/wine


echo '{"country": "Italy","year": 2008,"type": "Morellino di Scansano - HEBA","producer": "Fattoria DiMagliano","quantity": 4,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Morellino di Scansano - HEBA","producer": "Fattoria DiMagliano","quantity": 4,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Taneto","producer": "Badia di Morrona","quantity": 24,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Taneto","producer": "Badia di Morrona","quantity": 24,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2004,"type": "San Giovese","producer": "Santa Cristina","quantity": 8,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2004,"type": "San Giovese","producer": "Santa Cristina","quantity": 8,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "tre Rosso Toscana","producer": "Bran Caia","quantity": 8,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "tre Rosso Toscana","producer": "Bran Caia","quantity": 8,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2001,"type": "Amarone Classico","producer": "Yillalta","quantity": 8,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2001,"type": "Amarone Classico","producer": "Yillalta","quantity": 8,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Caburnio","producer": "Moreiteti","quantity": 10,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Caburnio","producer": "Moreiteti","quantity": 10,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2004,"type": "Cariganano Del Saleis - Superior","producer": "Arruga","quantity": 9,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2004,"type": "Cariganano Del Saleis - Superior","producer": "Arruga","quantity": 9,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine

echo '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Il Palazzone","quantity": 12,"cellarLocation": "Bottom Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Il Palazzone","quantity": 12,"cellarLocation": "Bottom Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2011,"type": "Le Volte","producer": "Dell '"'"'Ornellaia","quantity": 5,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2011,"type": "Le Volte","producer": "Dell '"'"'Ornellaia","quantity": 5,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2012,"type": "Brunello di Montalcino","producer": "Il Poggione","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2012,"type": "Brunello di Montalcino","producer": "Il Poggione","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Montepulciano D'"'"'Abruzzo - Riserva","producer": "Spelt","quantity": 11,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Montepulciano D'"'"'Abruzzo - Riserva","producer": "Spelt","quantity": 11,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2006,"type": "Aglianico","producer": "irpinia","quantity": 1,"cellarLocation": "Left Side","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2006,"type": "Aglianico","producer": "irpinia","quantity": 1,"cellarLocation": "Left Side","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2011,"type": "Barbaresco","producer": "Cantina Del Nebbiolo","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2011,"type": "Barbaresco","producer": "Cantina Del Nebbiolo","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2012,"type": "Primitivo Di Duria","producer": "Jorche","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2012,"type": "Primitivo Di Duria","producer": "Jorche","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Casanova di Neria - Tenuta Nuova","quantity": 5,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Casanova di Neria - Tenuta Nuova","quantity": 5,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Casanova di Neria - Tenuta Nuova","quantity": 1,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false,"notes": "Anniversary Label"}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Casanova di Neria - Tenuta Nuova","quantity": 1,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false,"notes": "Anniversary Label"}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Salciutti","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Salciutti","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Caparzo","quantity": 7,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Brunello di Montalcino","producer": "Caparzo","quantity": 7,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Bolgheri Superiore","producer": "Sondraia","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Bolgheri Superiore","producer": "Sondraia","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2013,"type": "Ilatraia","producer": "Bran Caia","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2013,"type": "Ilatraia","producer": "Bran Caia","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2012,"type": "Memini","producer": "Irpinia Aglianico","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2012,"type": "Memini","producer": "Irpinia Aglianico","quantity": 6,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2012,"type": "Brunello di Montalcino","producer": "Ucceliera","quantity": 12,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2012,"type": "Brunello di Montalcino","producer": "Ucceliera","quantity": 12,"cellarLocation": "Top Right","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine

echo '{"country": "Italy","year": 2009,"type": "Aglianico del Vulture","producer": "Serra del Preste","quantity": 7,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2009,"type": "Aglianico del Vulture","producer": "Serra del Preste","quantity": 7,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2009,"type": "Brunello di Montalcino - Riserva","producer": "La Lecciaia","quantity": 5,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2009,"type": "Brunello di Montalcino - Riserva","producer": "La Lecciaia","quantity": 5,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Brunello di Montalcino ","producer": "Valdicava","quantity": 28,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Brunello di Montalcino ","producer": "Valdicava","quantity": 28,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2006,"type": "Brunello di Montalcino ","producer": "Castel Giocondo","quantity": 5,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2006,"type": "Brunello di Montalcino ","producer": "Castel Giocondo","quantity": 5,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2010,"type": "Brunello di Montalcino - Riserva","producer": "Amantis","quantity": 6,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2010,"type": "Brunello di Montalcino - Riserva","producer": "Amantis","quantity": 6,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2000,"type": "Barolo","producer": "Raineri. Monserra","quantity": 12,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2000,"type": "Barolo","producer": "Raineri. Monserra","quantity": 12,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2010,"type": "Barbaresco","producer": "Icardi Montabert","quantity": 1,"bottleSize": 3000,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2010,"type": "Barbaresco","producer": "Icardi Montabert","quantity": 1,"bottleSize": 3000,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2010,"type": "Brunello di Montalcino ","producer": "Val di Suga","quantity": 6,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2010,"type": "Brunello di Montalcino ","producer": "Val di Suga","quantity": 6,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Scacciadiavoli","producer": "Montefalco Sagrantino","quantity": 1,"bottleSize": 3000,"originalWoodenCase": true}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Scacciadiavoli","producer": "Montefalco Sagrantino","quantity": 1,"bottleSize": 3000,"originalWoodenCase": true}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2011,"type": "Darmagi","producer": "Gaja","quantity": 1,"bottleSize": 1500,"originalWoodenCase": true}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2011,"type": "Darmagi","producer": "Gaja","quantity": 1,"bottleSize": 1500,"originalWoodenCase": true}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2012,"type": "Toscanna","producer": "Collazzi","quantity": 6,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2012,"type": "Toscanna","producer": "Collazzi","quantity": 6,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1995,"type": "Sassicaia","producer": "Antinoria","quantity": 6,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1995,"type": "Sassicaia","producer": "Antinoria","quantity": 6,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1999,"type": "Sassicaia","producer": "Antinoria","quantity": 6,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1999,"type": "Sassicaia","producer": "Antinoria","quantity": 6,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2010,"type": "Tignanello","producer": "Antinori","quantity": 12,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2010,"type": "Tignanello","producer": "Antinori","quantity": 12,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2010,"type": "Brunello di Montalcino ","producer": "Altesino","quantity": 5,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2010,"type": "Brunello di Montalcino ","producer": "Altesino","quantity": 5,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Chianti Classico Riserva","producer": "La Maialina","quantity": 7,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Chianti Classico Riserva","producer": "La Maialina","quantity": 7,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2004,"type": "Barbaresco","producer": "Sottimano Cottá","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2004,"type": "Barbaresco","producer": "Sottimano Cottá","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2006,"type": "Barolo","producer": "Cerequio","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2006,"type": "Barolo","producer": "Cerequio","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Barbaresco - Reiserva","producer": "Orello","quantity": 5,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Barbaresco - Reiserva","producer": "Orello","quantity": 5,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Barbaresco - Reiserva","producer": "Asili","quantity": 4,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Barbaresco - Reiserva","producer": "Asili","quantity": 4,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2004,"type": "Barbaresco - Reiserva","producer": "Poro","quantity": 2,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2004,"type": "Barbaresco - Reiserva","producer": "Poro","quantity": 2,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Barbaresco - Reiserva","producer": "Ovello","quantity": 4,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Barbaresco - Reiserva","producer": "Ovello","quantity": 4,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Barbaresco - Reiserva","producer": "Asili","quantity": 4,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Barbaresco - Reiserva","producer": "Asili","quantity": 4,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1997,"type": "Barbaresco","producer": "Gaja","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1997,"type": "Barbaresco","producer": "Gaja","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2006,"type": "Barolo","producer": "Gaja","quantity": 5,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2006,"type": "Barolo","producer": "Gaja","quantity": 5,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Ca'"'"'Marcanda - Promis","producer": "Gaja","quantity": 2,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Ca'"'"'Marcanda - Promis","producer": "Gaja","quantity": 2,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1990,"type": "Barolo","producer": "Bricco Rocche","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1990,"type": "Barolo","producer": "Bricco Rocche","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Barolo","producer": "Azelia San Rocco","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Barolo","producer": "Azelia San Rocco","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Caburnio","producer": "Monteti","quantity": 8,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Caburnio","producer": "Monteti","quantity": 8,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2010,"type": "Roso di Montalcino","producer": "Uccelliera","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2010,"type": "Roso di Montalcino","producer": "Uccelliera","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Barbaresco - Reiserva","producer": "Rabasa","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Barbaresco - Reiserva","producer": "Rabasa","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine

echo '{"country": "Italy","year": 1998,"type": "Barolo","producer": "Oddero","quantity": 15,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1998,"type": "Barolo","producer": "Oddero","quantity": 15,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1999,"type": "Taurasi","producer": "Radici","quantity": 6,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1999,"type": "Taurasi","producer": "Radici","quantity": 6,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1999,"type": "Toscana - Tenuta","producer": "Neita","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1999,"type": "Toscana - Tenuta","producer": "Neita","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1999,"type": "Toscana","producer": "Lucilla","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1999,"type": "Toscana","producer": "Lucilla","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1999,"type": "Tignanello","producer": "Antinori","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1999,"type": "Tignanello","producer": "Antinori","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2003,"type": "Vigneto Ilumlino","producer": "Nemo","quantity": 2,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2003,"type": "Vigneto Ilumlino","producer": "Nemo","quantity": 2,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2004,"type": "Brunello di Montalcino","producer": "Vaspicava","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2004,"type": "Brunello di Montalcino","producer": "Vaspicava","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2005,"type": "Berbera D'"'"'Asti Superore","producer": "-","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2005,"type": "Berbera D'"'"'Asti Superore","producer": "-","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2006,"type": "Montepulciano D'"'"'Abruzzo","producer": "Villamedoro","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2006,"type": "Montepulciano D'"'"'Abruzzo","producer": "Villamedoro","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2006,"type": "Aglianico Cinque Cuerce","producer": "Irpinia","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2006,"type": "Aglianico Cinque Cuerce","producer": "Irpinia","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Barolo","producer": "Cannubi","quantity": 2,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Barolo","producer": "Cannubi","quantity": 2,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Chianti Rufina - Riserva","producer": "Nipozzano","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Chianti Rufina - Riserva","producer": "Nipozzano","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2004,"type": "Barolo","producer": "Revello","quantity": 2,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2004,"type": "Barolo","producer": "Revello","quantity": 2,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2005,"type": "Brunello di Montalcino","producer": "Tenutavitanza","quantity": 4,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2005,"type": "Brunello di Montalcino","producer": "Tenutavitanza","quantity": 4,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Vino Nobile di Montepulciano","producer": "Costello di Pirro","quantity": 2,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Vino Nobile di Montepulciano","producer": "Costello di Pirro","quantity": 2,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Montepulciano ","producer": "Montevetrano","quantity": 2,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Montepulciano ","producer": "Montevetrano","quantity": 2,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Montepulciano ","producer": "Montevetrano","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Montepulciano ","producer": "Montevetrano","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Brunello di Montalcino","producer": "Uccelliera","quantity": 10,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Brunello di Montalcino","producer": "Uccelliera","quantity": 10,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Taurasi","producer": "Cantine Antonio Caggiano","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Taurasi","producer": "Cantine Antonio Caggiano","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2008,"type": "Barbera","producer": "Colli Tortonesi","quantity": 7,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2008,"type": "Barbera","producer": "Colli Tortonesi","quantity": 7,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 1990,"type": "Brunello di Montalcino","producer": "Caparzo","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 1990,"type": "Brunello di Montalcino","producer": "Caparzo","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2009,"type": "Chianti Classico","producer": "Monsanto","quantity": 2,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2009,"type": "Chianti Classico","producer": "Monsanto","quantity": 2,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2009,"type": "Barolo","producer": "Enrico Serafino","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2009,"type": "Barolo","producer": "Enrico Serafino","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2004,"type": "Barbaresco","producer": "Sottimano - Cottá","quantity": 10,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2004,"type": "Barbaresco","producer": "Sottimano - Cottá","quantity": 10,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2002,"type": "Taurasi Riserva","producer": "Rajamagra","quantity": 3,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2002,"type": "Taurasi Riserva","producer": "Rajamagra","quantity": 3,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2007,"type": "Vino Nobile De M","producer": "Avignonesi","quantity": 1,"bottleSize": 1500,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2007,"type": "Vino Nobile De M","producer": "Avignonesi","quantity": 1,"bottleSize": 1500,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Italy","year": 2010,"type": "Chianti Vlassico Riserva","producer": "Rancia ","quantity": 2,"bottleSize": 1500,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Italy","year": 2010,"type": "Chianti Vlassico Riserva","producer": "Rancia ","quantity": 2,"bottleSize": 1500,"originalWoodenCase": false}' http://localhost:8081/wine

echo '{"country": "United States","year": 1991,"type": "Opus One","producer": "Opus One","quantity": 8,"cellarLocation": "Top Left","bottleSize": 375,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "United States","year": 1991,"type": "Opus One","producer": "Opus One","quantity": 8,"cellarLocation": "Top Left","bottleSize": 375,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "United States","year": 2011,"type": "Pinot Noir Reserve","producer": "Domaine Serene (OR)","quantity": 3,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "United States","year": 2011,"type": "Pinot Noir Reserve","producer": "Domaine Serene (OR)","quantity": 3,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "United States","year": 2011,"type": "Pinot Noir","producer": "Evening Land (OR)","quantity": 4,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "United States","year": 2011,"type": "Pinot Noir","producer": "Evening Land (OR)","quantity": 4,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "United States","year": 2013,"type": "Pinot Noir","producer": "Acacia (CA)","quantity": 8,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "United States","year": 2013,"type": "Pinot Noir","producer": "Acacia (CA)","quantity": 8,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "United States","year": 2013,"type": "Pinot Noir","producer": "The Calling (CA)","quantity": 8,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "United States","year": 2013,"type": "Pinot Noir","producer": "The Calling (CA)","quantity": 8,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "United States","year": 2014,"type": "Pinot Noir","producer": "Etude (CA)","quantity": 4,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "United States","year": 2014,"type": "Pinot Noir","producer": "Etude (CA)","quantity": 4,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "United States","year": 2010,"type": "Pinot Noir","producer": "Merry Edwards (CA)","quantity": 1,"cellarLocation": "Top Left","bottleSize": 1500,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "United States","year": 2010,"type": "Pinot Noir","producer": "Merry Edwards (CA)","quantity": 1,"cellarLocation": "Top Left","bottleSize": 1500,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "United States","year": 2015,"type": "Pinot Noir","producer": "L'"'"'En Voyé - Two Messengers (OR)","quantity": 5,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "United States","year": 2015,"type": "Pinot Noir","producer": "L'"'"'En Voyé - Two Messengers (OR)","quantity": 5,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "United States","year": 2016,"type": "Pinot Noir","producer": "Elnuan (OR)","quantity": 5,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "United States","year": 2016,"type": "Pinot Noir","producer": "Elnuan (OR)","quantity": 5,"cellarLocation": "Top Left","bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Portugal","year": 1977,"type": "Port","producer": "Dow'"'"'s","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Portugal","year": 1977,"type": "Port","producer": "Dow'"'"'s","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
echo '{"country": "Portugal","year": 1985,"type": "Port","producer": "W&J Graham'"'"'s","quantity": 1,"bottleSize": null,"originalWoodenCase": false}'  && curl -H "content-type: application/json" --request POST --data '{"country": "Portugal","year": 1985,"type": "Port","producer": "W&J Graham'"'"'s","quantity": 1,"bottleSize": null,"originalWoodenCase": false}' http://localhost:8081/wine
