spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wine-test
    password: winepwd
    username: wineuser
  flyway:
    locations: classpath:db/migrations
  mvc:
    static-path-pattern: /app/**

server:
  port: 8081
