version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: user
      PGDATA: /database

  unit-integration-tests:
    image: openjdk
    privileged: true
    links: [db]
    depends_on: [db]
    command: "./repo/ci/tasks/run-backend-tests-exe.sh"
    volumes:
      - ../:/repo