---
resources:

- name: repo
  type: git
  source:
    uri: ((git-repo))
    private_key: ((github-private-key))

- name: openjdk
  type: docker-image
  source:
    repository: openjdk
    tag: 8

- name: postgres
  type: docker-image
  source:
    repository: postgres

- name: cypress-image
  type: docker-image
  source:
    repository: cypress/browsers
    tag: chrome67

- name: dcind
  type: docker-image
  source:
    repository: amidos/dcind

- name: openjdk-node-cf
  type: docker-image
  source:
    repository: djdapz/openjdk-node-cf

- name: acceptance
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((PCF_USERNAME))
    password: ((PCF_PASSWORD))
    organization: dapuzzo
    space: development

- name: production
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((PCF_USERNAME))
    password: ((PCF_PASSWORD))
    organization: dapuzzo
    space: production

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:djdapz/wine-inventory.git
    branch: version
    file: version
    private_key: ((github-private-key))

- name: frontend-s3
  type: s3
  source:
    region_name: us-west-2
    bucket: wine-inventory
    regexp: app/frontend-(.*).zip
    access_key_id: ((AWS_ACCESS_KEY_ID))
    secret_access_key: ((AWS_SECRET_ACCESS_KEY))

- name: backend-s3
  type: s3
  source:
    region_name: us-west-2
    bucket: wine-inventory
    regexp: app/backend-(.*).jar
    access_key_id: ((AWS_ACCESS_KEY_ID))
    secret_access_key: ((AWS_SECRET_ACCESS_KEY))

jobs:

- name: run-tests-backend
  public: true
  plan:
    - get: version
    - get: repo
      trigger: true
    - get: openjdk
      params: {save: true}
    - get: postgres
      params: {save: true}
    - get: dcind
      params: {save: true}
    - task: run-tests
      privileged: true
      image: dcind
      config:
        platform: linux
        inputs:
          - name: repo
          - name: postgres
          - name: openjdk
        run:
          path: sh
          args:
          - -exc
          - |
            set -e
            source /docker-lib.sh

            start_docker

            docker load -i postgres/image
            docker tag "$(cat postgres/image-id)" "$(cat postgres/repository):$(cat postgres/tag)"

            docker load -i openjdk/image
            docker tag "$(cat openjdk/image-id)" "$(cat openjdk/repository):$(cat openjdk/tag)"


            docker images

            docker-compose -f repo/ci/docker-compose.tests.yml run unit-integration-tests

            docker-compose -f repo/ci/docker-compose.tests.yml down
            docker volume rm $(docker volume ls -q)
    - put: version
      params: {bump: patch}

- name: run-tests-frontend
  public: true
  plan:
    - get: version
    - get: repo
      trigger: true
    - get: cypress-image
      params: {save: true}
    - task: run-tests
      privileged: true
      image: cypress-image
      config:
        platform: linux
        inputs:
          - name: repo
        caches:
          - path: repo/frontend/node_modules
          - path: ../../../root/.cache
        run:
          path: sh
          args:
            - -exc
            - |
              set -e
              cd repo/frontend
              ls -lsa node_modules
              npm i
              npm run test:int:ci


- name: build-and-upload-frontend
  public: true
  plan:
    - get: version
      trigger: true
      passed: ["run-tests-backend", 'run-tests-frontend']
    - get: repo
      trigger: true
      passed: ["run-tests-backend", 'run-tests-frontend']
    - get: openjdk-node-cf
      params: {save: true}
    - task: build-and-upload
      privileged: true
      image: openjdk-node-cf
      config:
        platform: linux
        inputs:
          - name: repo
          - name: version
        outputs:
          - name: frontend-s3
        caches:
          - path: repo/frontend/node_modules
          - path: ../../../root/.cache
        run:
          path: sh
          args:
            - -exc
            - |
              #!/bin/bash

              set -ex

              export BUILD_VERSION=`cat version/number`

              cd repo/frontend
              npm install
              npm run build

              touch build/Staticfile
              cd build
              zip -r ../../../frontend-s3/frontend-${BUILD_VERSION}.zip *

              cp "./frontend.zip" "s3://wine-inventory/app/frontend-${BUILD_VERSION}.zip"
    - put: frontend-s3
      params:
        file: frontend-s3/frontend-*.zip


- name: build-and-upload-backend
  public: true
  plan:
    - get: version
      trigger: true
      passed: ["run-tests-backend"]
    - get: repo
      trigger: true
      passed: ["run-tests-backend"]
    - get: openjdk-node-cf
      params: {save: true}
    - task: build-and-upload
      privileged: true
      image: openjdk-node-cf
      config:
        platform: linux
        inputs:
          - name: repo
          - name: version
        outputs:
          - name: backend-s3
        caches:
          - path: gradle
        run:
          path: sh
          args:
          - -exc
          - |
            #!/bin/bash

            set -ex

            ./repo/ci/tasks/cache_gradle.sh

            export BUILD_VERSION=`cat version/number`

            cd repo
            ./gradlew clean assemble -Pversion=$BUILD_VERSION

            ls -lsa build/libs

            cp "build/libs/wine-inventory-${BUILD_VERSION}.jar" "../backend-s3/wine-inventory-${BUILD_VERSION}.jar"
    - put: backend-s3
      params:
        file: backend-s3/backend-*.jar

- name: deploy-acceptance
  plan:
  - get: version
    trigger: true
    passed: ["build-and-upload-backend", "build-and-upload-frontend"]
  - get: repo
    trigger: true
    passed: ["build-and-upload-backend", "build-and-upload-frontend"]
  - get: openjdk-node-cf
    params: {save: true}
  - task: download-jar
    privileged: true
    image: openjdk-node-cf
    config:
      platform: linux
      inputs:
      - name: repo
      - name: version
      outputs:
      - name: deploy
      run:
        path: sh
        args:
        - -exc
        - |
          #!/bin/bash

          export BUILD_VERSION=`cat version/number`

          set -ex

          /root/bin/aws s3 cp  "s3://wine-inventory/app/wine-inventory-${BUILD_VERSION}.jar"  ./deploy/backend.jar
          cp ./repo/ci/manifests/acceptance/mainfest-backend.yml ./deploy/manifest-backend.yml

          /root/bin/aws s3 cp  "s3://wine-inventory/app/frontend-${BUILD_VERSION}.zip"  ./deploy/frontend.zip
          cp ./repo/ci/manifests/acceptance/mainfest-frontend.yml ./deploy/manifest-frontend.yml
          export BUILD_VERSION=`cat version/number`

      params:
        AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
        AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
  - put: acceptance
    params:
      inputs:
      - name: deploy
      path: deploy/backend.jar
      manifest: deploy/manifest-backend.yml
  - put: acceptance
    params:
      inputs:
      - name: deploy
      path: deploy/frontend.zip
      manifest: deploy/manifest-frontend.yml

- name: deploy-backend-production
  plan:
  - get: version
    trigger: false
    passed: ["deploy-acceptance"]
  - get: repo
    trigger: false
    passed: ["deploy-acceptance"]
  - get: openjdk-node-cf
    params: {save: true}
  - task: download-jar
    privileged: true
    image: openjdk-node-cf
    config:
      platform: linux
      inputs:
      - name: repo
      - name: version
      outputs:
      - name: deploy
      run:
        path: sh
        args:
        - -exc
        - |
          #!/bin/bash

           export BUILD_VERSION=`cat version/number`

           /root/bin/aws s3 cp  "s3://wine-inventory/app/wine-inventory-${BUILD_VERSION}.jar"  ./deploy/backend.jar
           cp ./repo/ci/manifests/production/mainfest-backend.yml ./deploy/manifest-backend.yml

           /root/bin/aws s3 cp  "s3://wine-inventory/app/frontend-${BUILD_VERSION}.zip"  ./deploy/frontend.zip
           cp ./repo/ci/manifests/production/mainfest-frontend.yml ./deploy/manifest-frontend.yml
      params:
        AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
        AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
  - put: production
    params:
      inputs:
      - name: deploy
      path: deploy/frontend.zip
      manifest: deploy/manifest-frontend.yml
  - put: production
    params:
      inputs:
      - name: deploy
      path: deploy/backend.jar
      manifest: deploy/manifest-backend.yml
