name: Backend CI

on:
  push:
    branches: master

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: wine-test
          POSTGRES_PASSWORD: winepwd
          POSTGRES_USER: wineuser
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test and Build
        run: ./gradlew clean test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
#
#      - name: Cypress run
#        uses: cypress-io/github-action@v2
#        with:
#          working-directory: frontend
#          build: npm run build
#          start: npm start
#          wait-on: http://localhost:3210
#        env:
#          PORT: 3210

      - name: Test and Build
        run: cd frontend && npm run test

  build-and-deploy:
    needs:
      - test-frontend
      - test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: npm i
        run: cd frontend && npm i
      - name: Test and Build
        run: ./gradlew clean assemble -x test

      - name: Heroku Login
        run: heroku plugins:install java
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy Container
        run: heroku deploy:jar build/libs/wine-inventory-NO_VERSION.jar -a wine-inventory-djd
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
